### ISSUE TITLE
Clarification on aMAZEing needed

### ISSUE THREAD

**Issue by shilch** [tastelessctf/ctf2020#1]
Hello,

thanks for the challenge and the writeups, really enjoyed it!

What I'm still struggling with is understanding how aMAZEing is supposed to be solved:  
How I understand it is that the flag is encoded bitwise in the `addls pc, pc, r3, lsl #2` instruction at the beginning of each switch case. Encoding of a 1 bit is done by dropping the condition `ls` (i.e. swapping the `9` nibble with an `e` nibble).  

However, in the `maze` binary uploaded here on GitHub, no such mutation can be found:  
```
$ objdump -d maze | fgrep '908ff103' | wc -l
7442
$ objdump -d maze | fgrep 'e08ff103' | wc -l
0
```  
I believe it's the same binary as during the challenge which is no longer present in my fs (I would have noticed if a switch case started with a normal `add` instruction).

Am I missing something here?

Thanks!

**Comment by nSinus-R** [comment]
Hi!

Your intuition is almost right, but not completely! The flag is not encoded inside the addls instruction, but in the branch+link instructions taken to get through the maze. These branches are either `bl` or `blls` instructions - as the less flag is always set when a branch to the next function is carried out, the two instructions act equally in this specific case.

The `addls` instruction you mentioned is just needed by the solve/verify script for trace-adjustement. In general, this instruction selects the entrypoint in the following branchtable (and, btw, also ensures that the less flag is set). In an instruction trace, this instruction will always be executed just right before the `bl` or `blls`, hence, I used it for adjustement.

The binary here in the repo is the same as handed out in the tournament.

**Comment by shilch** [comment]
Ah, okay. That makes sense. Thank you!
